proxy:
    - name: tcp_proxy
      config:
        host: 0.0.0.0 # Local ip/hostname to bind to and accept connections.
        port: 61618 # Local port to bind to
        proxy_host: activemq
        proxy_port: 61617
        nagles_algorithm: true
        packet_size: 64

middleware:
  - name: network_shape
    config:
      latency: 250 # Latency to add in ms
      target_bw: 750 # Bandwidth in kbits/s
      packet_loss: 0.5 # Packet loss, as a %
      target_ips: # Target ipv4 IP addresses
        - 0.0.0.0
      target_ips6: # Target ipv6 IP addresses
        - "::1/128"
      target_ports: # Target destination ports
        - "80"
      target_protos: # Target protocols
        - "tcp"
        - "udp"
        - "icmp"
      device: "lo" # defaults to eth0